
<style>
    .titulo {
	color: #2D5D89;
	font-weight: 700;
	text-align: center;
	margin: 10px 0;
}
</style>
<div class="about-info cms-content">
    <div class="row">
        <div class="col-1"></div>
        <div class="col-10">
            <h2 class="text-center titulo">FACTURACIÓN</h2>
            <h3 class="text-center titulo">Bienvenido al módulo de facturación</h3>
            <p class="text-justify">
                Bienvenido a la sección de facturación, aquí puedes solicitar factura de tus compras de manera rápida y sencilla. A continuación, te explicamos cómo hacerlo:<br><br>

                1.	Indícanos el número de pedido o folio de tu orden<br>
                2.	Registra tu información en los campos solicitados, o si lo prefieres adjunta tu constancia de situación fiscal<br>
                3.	Ingresa los datos de contacto a los que enviaremos la factura<br>
                4.	Déjanos algún comentario a considerar para efectos de la facturación.<br><br>

                Recibirás tu factura en un plazo no mayor a 48 horas en presentación PDF y XML, recomendamos revisar la carpeta de correo no deseado en caso de no encontrar tu factura en la bandeja principal. Si necesitas asistencia durante el proceso o tienes alguna pregunta, nuestro equipo de atención al cliente está listo para ayudarte; no dudes en contactarnos por el medio de tu preferencia.

            </p>
            <br>
            <br>  
        </div>
        <div class="col-6"></div>
    </div>    
</div>
<div class="row">
    <div class="col-1">
    </div>
    <div class="col-10">
        <form method="POST" action="<?= $block->escapeUrl($block->getFormAction()) ?>" enctype="multipart/form-data">      
            <h3 class="text-center titulo">Datos de facturación </h3>
            <div class="row">
                <div class="col-4 form-control"> 
                    <label for="name">Folio Pedido o No. Orden: <span style="color: red;">*</span></label> 
                    <input class="form-control" type="text" id="name" name="foliopedido" placeholder="Folio Pedido o No. Orden"  required> 
                </div>           
                <div class="col-4 form-control"> 
                    <label for="name">Razón Social: <span style="color: red;">*</span></label> 
                    <input class="form-control" type="text" id="name" name="razonsocial" placeholder="Razón Social" required>
                </div>               
                <div class="col-4 form-control"> 
                    <label for="name">Persona Física o Moral: <span style="color: red;">*</span></label> 
                    <select class="form-control" name="fisicamoral" required>
                        <option value="0">--Seleccione--</option>
                        <option value="Fisica">Fisica</option>
                        <option value="Moral">Moral</option>
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="col-4 form-control"> 
                    <label for="name">RFC: <span style="color: red;">*</span></label> 
                    <input class="form-control" type="text" id="name" name="rfc" placeholder="RFC"  required>
                </div>
                <div class="col-4 form-control"> 
                    <label for="name">Regimen Fiscal: <span style="color: red;">*</span></label> 
                    <select id="regimenfiscal" class="form-control" name="regimenfiscal" required>
                        <option value="0">--Seleccione--</option>
                        <option value="601 – General de Ley Personas Morales">601 – General de Ley Personas Morales</option>
                        <option value="603 – Personas Morales con Fines no Lucrativos">603 – Personas Morales con Fines no Lucrativos</option>
                        <option value="605 – Sueldos y Salarios e Ingresos Asimilados a Salarios">605 – Sueldos y Salarios e Ingresos Asimilados a Salarios</option>
                        <option value="606 – Arrendamiento">606 – Arrendamiento</option>
                        <option value="607 – Régimen de Enajenación o Adquisición de Bienes">607 – Régimen de Enajenación o Adquisición de Bienes</option>
                        <option value="608 – Demás ingresos">608 – Demás ingresos</option>
                        <option value="609 – Consolidación">609 – Consolidación</option>
                        <option value="610 – Residentes en el Extranjero sin Establecimiento">610 – Residentes en el Extranjero sin Establecimiento</option>
                        <option value="611 – Ingresos por Dividendos (socios y accionistas)">611 – Ingresos por Dividendos (socios y accionistas)</option>
                        <option value="612 – Personas Físicas con Actividades Empresariales y Profesionales">612 – Personas Físicas con Actividades Empresariales y Profesionales</option>
                        <option value="614 – Ingresos por intereses">614 – Ingresos por intereses</option>
                        <option value="616 – Sin Obligaciones Fiscales">616 – Sin Obligaciones Fiscales</option>
                        <option value="620 – Sociedades Cooperativas de Producción que optan por diferir sus ingresos">620 – Sociedades Cooperativas de Producción que optan por diferir sus ingresos</option>
                        <option value="621 – Incorporación Fiscal">621 – Incorporación Fiscal</option>
                        <option value="622 – Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras con opción de diferimiento">622 – Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras con opción de diferimiento</option>
                        <option value="623 – Opcional para grupos de sociedades">623 – Opcional para grupos de sociedades</option>
                        <option value="624 – De los Coordinados">624 – De los Coordinados</option>
                        <option value="625 – Régimen de las Actividades Empresariales con ingresos a través de Plataformas">625 – Régimen de las Actividades Empresariales con ingresos a través de Plataformas</option>
                        <option value="626 – Regimen simplificado de confianza">626 – Regimen simplificado de confianza</option>
                        <option value="634 – Del Régimen de los bienes usados">634 – Del Régimen de los bienes usados</option>
                        <option value="636 – De los Regímenes Fiscales Preferentes y de las Empresas Multinacionales">636 – De los Regímenes Fiscales Preferentes y de las Empresas Multinacionales</option>
                    </select>
                </div>
                <div class="col-4 form-control"> 
                    <label for="name">Uso de CFDI: <span style="color: red;">*</span></label> 
                    <select class="form-control" name="cfdi" required>
                        <option value="0">--Seleccione--</option>
                        <option value="1 – Efectivo">1 – Efectivo</option>
                        <option value="2 – Cheque">2 – Cheque</option>
                        <option value="3 – Transferencia electrónica">3 – Transferencia electrónica</option>
                        <option value="4 – Tarjeta de crédito">4 – Tarjeta de crédito</option>
                        <option value="28 – Tarjeta de débito">28 – Tarjeta de débito</option>
                        <option value="29 – Tarjeta de servicios">29 – Tarjeta de servicios</option>
                        <option value="30 – Aplicación de anticipos">30 – Aplicación de anticipos</option>
                        <option value="31 – Intermediario pagos">31 – Intermediario pagos</option>
                        <option value="60 – Pago por internet">60 – Pago por internet</option>
                        <option value="61 – Servicios prestados por medios electrónicos">61 – Servicios prestados por medios electrónicos</option>
                        <option value="63 – Pago por terceros">63 – Pago por terceros</option>
                        <option value="65 – Pago por internet con intermediario pagos">65 – Pago por internet con intermediario pagos</option>
                    </select>
                </div>                
            </div>
            <div class="row">
                <div class="col-4 form-control"> 
                    <label for="name">Método de pago: <span style="color: red;">*</span></label> 
                    <input class="form-control" type="text" id="metodopago" name="rfc" placeholder="Método de pago"  required>
                </div>
                <div class="col-4 form-control"> 
                    <label for="name">Importe (Incluye IVA): <span style="color: red;">*</span></label> 
                    <input class="form-control" type="text" id="importeiva" name="importeiva" placeholder="Importe (Incluye IVA)"  required>
                </div>
            </div>
            <br>
            <h3 class="text-center titulo">Domicilio Fiscal</h3>
            <div class="row">
                <div class="col-3 form-control"> 
                    <label for="name">Calle del domicilio: <span style="color: red;">*</span></label> 
                    <input class="form-control" type="text" id="name" name="calle" placeholder="Calle del domicilio"  required> 
                </div>
                <div class="col-3 form-control">
                    <label for="name">Número Externo: <span style="color: red;">*</span></label> 
                    <input class="form-control" type="text" id="name" name="noexterno" placeholder="Número Externo" required>
                </div>
                <div class="col-3 form-control"> 
                    <label for="name">No. Interno: <span style="color: red;">*</span></label> 
                    <input class="form-control" type="text" id="name" name="nointerno" placeholder="No. Interno" >
                </div>
                <div class="col-3 form-control"> 
                    <label for="name">Ciudad: <span style="color: red;">*</span></label> 
                    <input class="form-control" type="text" id="name" name="ciudad" placeholder="Ciudad" >
                </div>                    
            </div>
            <div class="row">
                <div class="col-3 form-control"> 
                    <label for="name">Colonia: <span style="color: red;">*</span></label> 
                    <input class="form-control" type="text" id="name" name="colonia" placeholder="Colonia"  >
                </div>
                <div class="col-3 form-control"> 
                    <label for="name">Municipio: <span style="color: red;">*</span></label> 
                    <input class="form-control" type="text" id="name" name="municipio" placeholder="Municipio"  required>
                </div>
                <div class="col-3 form-control"> 
                    <label for="name">Estado: <span style="color: red;">*</span></label> 
                    <input class="form-control" type="text" id="name" name="estado" placeholder="Estado"  required>
                </div>
                <div class="col-3 form-control"> 
                    <label for="name">Código Postal: <span style="color: red;">*</span></label> 
                    <input class="form-control" type="text" id="name" name="codigopostal" placeholder="Código Postal"  required>
                </div>
            </div>  
            <br>
            <h3 class="text-center titulo">Datos de contacto</h3>              
            <div class="row">
                <div class="col-6 form-control"> 
                    <label for="name">Teléfono: <span style="color: red;">*</span></label> 
                    <input class="form-control" type="text" id="name" name="telefono" placeholder="Teléfono"  required> 
                </div>           
                <div class="col-6 form-control"> 
                    <label for="name">Correo Electrónico: <span style="color: red;">*</span></label> 
                    <input class="form-control" type="text" id="name" name="correoelec" placeholder="Correo Electrónico" required>
                </div> 
            </div>
            <div class="row">
                <div class="col-12 form-control"> 
                    <label for="name">Comentarios:<span style="color: red;">*</span></label> 
                    <textarea class="form-control" type="textarea" rows="8" id="name" name="comentarios" placeholder="Indícanos el código de los productos que deseas facturar, de no hacerlo se facturará la totalidad de los artículos incluidos en la orden." required></textarea>            
                </div> 
            </div>           
            <br>            
            <div class="col-12 form-control"> 
                <label>Adjuntar Constancia de situación fiscal(Opcional):</label>
                <input type="file" name="archivo" />            
            </div>               
            <br>            
            <div class="col-12 text-center">
                <button class="btn btn-primary" type="submit" name="uploadBtn" value="Upload">Enviar datos para facturar</button>
            </div>              
        </form>
    </div>
    <div class="col-6">
    </div>
</div>
