<style>
    .titulo {
	color: #2D5D89;
	font-weight: 700;
	text-align: center;
	margin: 10px 0;
}
</style>
<div class="about-info cms-content">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-12">
            <h2 class="text-center titulo">FACTURACIÓN</h2>
            <h3 class="text-center titulo">Bienvenido al módulo de autofacturación Unilane</h3>
            <p class="text-justify">
                •	Ingresa el número o folio de orden para poder identificar tu compra<br>
                •	Nuestro sistema te proporcionará automáticamente la información de tu compra y solicitará los datos necesarios para emitirla.<br>
                •	Verifica cuidadosamente el nombre o razón social, RFC, dirección fiscal y cualquier otro dato que ingreses en los campos correspondientes antes de generar la factura.<br>
                •	Una vez emitida la factura, descárgala en formato PDF y verifica que todos los datos sean correctos. Revisa que tu nombre o razón social, RFC, dirección fiscal, descripción de los productos o servicios, precios y montos totales estén precisos y coincidan con tu compra. Si encuentras algún error o discrepancia, por favor contáctanos de inmediato para que podamos corregirlo.             
            </p>
            <br>
            <br>  
        </div>
        <div class="col-4"></div>
    </div>    
</div>
<div class="row">
    <div class="col-4">
    </div>
    <div class="col-12">
        <form method="POST" action="<?= $block->escapeUrl($block->getFormAction()) ?>" enctype="multipart/form-data">      
            <h3 class="text-center titulo">Datos de facturación </h3>
            <div class="col-12 form-control"> 
                <label for="name">Folio Pedido o No. Orden:<span style="color: red;">*</span></label> 
                <input class="form-control" type="text" id="name" name="foliopedido" placeholder="tu nombre completo o razón social"  required> 
            </div>           
            <div class="col-12 form-control"> 
                <label for="name">Razón Social:</label> 
                <input class="form-control" type="text" id="name" name="razonsocial" placeholder="Sitio web de tu empresa" required>
            </div>               
            <div class="col-12 form-control"> 
                <label for="name">Persona Física o Moral:<span style="color: red;">*</span></label> 
                <select class="form-control" name="fisicamoral" required>
                    <option value="Fisica">Fisica</option>
                    <option value="Moral">Moral</option>
                </select>
            </div>
            <div class="col-12 form-control"> 
                <label for="name">RFC:<span style="color: red;">*</span></label> 
                <input class="form-control" type="text" id="name" name="rfc" placeholder="Categoría de productos, separar por comas"  required>
            </div>
            <div class="col-12 form-control"> 
                <label for="name">Regimen Fiscal:<span style="color: red;">*</span></label> 
                <input class="form-control" type="text" id="name" name="regimenfiscal" placeholder="Marca(s) de los productos separar por comas"  required>
            </div>
            <div class="col-12 form-control"> 
                <label for="name">Uso de CFDI:<span style="color: red;">*</span></label> 
                <input class="form-control" type="text" id="name" name="cfdi" placeholder="Ubicación de su(s) bodega(s), separar por comas"  required>
            </div>
            <br>
            <h3 class="text-center titulo">Domicilio Fiscal</h3>
            <div class="col-12 form-control"> 
                <label for="name">Calle del domicilio:<span style="color: red;">*</span></label> 
                <input class="form-control" type="text" id="name" name="calle" placeholder="tu nombre completo"  required> 
            </div>           
            <div class="col-6 form-control"> 
                <label for="name">Número Externo:<span style="color: red;">*</span></label> 
                <input class="form-control" type="text" id="name" name="noexterno" placeholder="Apellidos" required>
            </div>               
            <div class="col-6 form-control"> 
                <label for="name">No. Interno:<span style="color: red;">*</span></label> 
                <input class="form-control" type="text" id="name" name="nointerno" placeholder="Telefono" >
            </div>
            <div class="col-12 form-control"> 
                <label for="name">Colonia:</label> 
                <input class="form-control" type="text" id="name" name="colonia" placeholder="Extensión"  >
            </div>
            <div class="col-12 form-control"> 
                <label for="name">Municipio:<span style="color: red;">*</span></label> 
                <input class="form-control" type="text" id="name" name="municipio" placeholder="Correo electrónico"  required>
            </div>
            <div class="col-12 form-control"> 
                <label for="name">Estado:<span style="color: red;">*</span></label> 
                <input class="form-control" type="text" id="name" name="estado" placeholder="Correo electrónico"  required>
            </div>
            <div class="col-12 form-control"> 
                <label for="name">Código Postal:<span style="color: red;">*</span></label> 
                <input class="form-control" type="text" id="name" name="codigopostal" placeholder="Correo electrónico"  required>
            </div>
            <br>
            <h3 class="text-center titulo">Datos de contacto</h3>
            <div class="col-12 form-control"> 
                <label for="name">Teléfono:<span style="color: red;">*</span></label> 
                <input class="form-control" type="text" id="name" name="telefono" placeholder="tu nombre completo"  required> 
            </div>           
            <div class="col-6 form-control"> 
                <label for="name">Correo Electrónico:<span style="color: red;">*</span></label> 
                <input class="form-control" type="text" id="name" name="correoelec" placeholder="Apellidos" required>
            </div> 
            <div class="col-12 form-control"> 
                <label>Adjuntar CSF:</label>
                <input type="file" name="archivo" />            
            </div>               
            <br>            
            <div class="col-12">
                <button class="btn btn-primary" type="submit" name="uploadBtn" value="Upload">Enviar datos para facturar</button>
            </div>              
        </form>
    </div>
    <div class="col-4">
    </div>
</div>
