<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Unilane\SyncProducts\Block\Adminhtml\System\Config\Form\Field\Import $block
 */
?>
<?= $block->getChildHtml('button'); ?>
<!-- <script type="text/x-magento-init">
{
    "*": {
        Unilane_SyncProducts/js/products
    }
}
</script> -->
<script>
require(['jquery'], function ($) {
    'use strict';
    $('#sync-products').click(function () {
        console.log("ejecucion");
        $.ajax({
        type: "POST",
        url: BASE_URL+'/syncproduct/products/importproducts?isAjax=true',
        data: {form_key: window.FORM_KEY},
        dataType: "json",
        showLoader: true,
        }).done(function (data) {
            console.log("si entra");
        });
    }); 
});
</script>

